apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: nfs-storage-provisioner
    creationTimestamp: "2020-10-08T18:15:23Z"
    finalizers:
    - kubernetes.io/pv-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-10-08T18:15:23Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/provisioned-by: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
          f:mountOptions: {}
          f:nfs:
            .: {}
            f:path: {}
            f:server: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: nfs-client-provisioner
      operation: Update
      time: "2020-10-08T18:15:23Z"
    name: pvc-8f56b720-4e5e-45a0-877d-87bd3d79772d
    resourceVersion: "19461"
    selfLink: /api/v1/persistentvolumes/pvc-8f56b720-4e5e-45a0-877d-87bd3d79772d
    uid: cfaee3f0-9586-4339-b279-13f8ed69c49c
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 100Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: image-registry-storage
      namespace: openshift-image-registry
      resourceVersion: "19161"
      uid: 8f56b720-4e5e-45a0-877d-87bd3d79772d
    mountOptions:
    - rw
    - relatime
    - vers=3
    - rsize=524288
    - wsize=524288
    - namlen=255
    - hard
    - intr
    - proto=tcp
    - timeo=600
    - retrans=2
    - sec=sys
    - mountvers=3
    - mountport=20048
    - mountproto=tcp
    - local_lock=all
    nfs:
      path: /exports/openshift-image-registry-image-registry-storage-pvc-8f56b720-4e5e-45a0-877d-87bd3d79772d
      server: 192.168.50.254
    persistentVolumeReclaimPolicy: Delete
    storageClassName: nfs-storage
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: nfs-storage-provisioner
    creationTimestamp: "2020-12-22T16:45:11Z"
    finalizers:
    - kubernetes.io/pv-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-12-22T16:45:11Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/provisioned-by: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
          f:mountOptions: {}
          f:nfs:
            .: {}
            f:path: {}
            f:server: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: nfs-client-provisioner
      operation: Update
      time: "2020-12-22T16:45:11Z"
    name: pvc-ded5972f-6ce3-4d23-b77e-cb06ce523d76
    resourceVersion: "1093024"
    selfLink: /api/v1/persistentvolumes/pvc-ded5972f-6ce3-4d23-b77e-cb06ce523d76
    uid: 1bfb0f30-6019-4064-831c-4cd136863c84
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: jenkins
      namespace: gitops-review
      resourceVersion: "1093017"
      uid: ded5972f-6ce3-4d23-b77e-cb06ce523d76
    mountOptions:
    - rw
    - relatime
    - vers=3
    - rsize=524288
    - wsize=524288
    - namlen=255
    - hard
    - intr
    - proto=tcp
    - timeo=600
    - retrans=2
    - sec=sys
    - mountvers=3
    - mountport=20048
    - mountproto=tcp
    - local_lock=all
    nfs:
      path: /exports/gitops-review-jenkins-pvc-ded5972f-6ce3-4d23-b77e-cb06ce523d76
      server: 192.168.50.254
    persistentVolumeReclaimPolicy: Delete
    storageClassName: nfs-storage
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
