apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "false"
    creationTimestamp: "2020-10-08T18:15:18Z"
    managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations: {}
        f:mountOptions: {}
        f:parameters:
          .: {}
          f:archiveOnDelete: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
      manager: OpenAPI-Generator
      operation: Update
      time: "2020-10-08T18:15:18Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:storageclass.kubernetes.io/is-default-class: {}
      manager: oc
      operation: Update
      time: "2020-12-23T08:07:56Z"
    name: nfs-storage
    resourceVersion: "1172124"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/nfs-storage
    uid: 72150310-047e-4ae9-96c9-807675c8ebfa
  mountOptions:
  - rw
  - relatime
  - vers=3
  - rsize=524288
  - wsize=524288
  - namlen=255
  - hard
  - intr
  - proto=tcp
  - timeo=600
  - retrans=2
  - sec=sys
  - mountvers=3
  - mountport=20048
  - mountproto=tcp
  - local_lock=all
  parameters:
    archiveOnDelete: "false"
  provisioner: nfs-storage-provisioner
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
